### ISSUE TITLE
Missing button feature

### ISSUE THREAD

**Issue by NicoOrz** [PJSoftCo/VGamepad#10]
The Press L/R sticker feature doesn't exist.

**Comment by pjsoftcoUser** [comment]
Do you mean the joystick hard press center button? 
![96765145-47C4-44DB-83D6-E51191243538](https://user-images.githubusercontent.com/4211206/121041213-2a9f0680-c778-11eb-8d13-29777a22beeb.jpeg)

if yes, it is only available on devices with 3D touch screens (pressure sensitive).

**Comment by NicoOrz** [comment]
Yea.But Today, iPhone doesn't have 3D touch anymore.I hope it can be a sigle button or any other way to achieve this.It is an important button in some time.

**Comment by pjsoftcoUser** [comment]
You are right, will consider it for the next update!

**Comment by pjsoftcoUser** [comment]
Updating both server-side software and the App will add theses two Thumb buttons to the controller, the IOS version is released and the Android version will be too.
