### ISSUE TITLE
VGamepad Driver popup not showing up

### ISSUE THREAD

**Issue by MiKoKappa** [PJSoftCo/VGamepad#12]
VGamepad Driver popup window not showing up after successfully connecting iPhone. This makes VGamepad unusable.

**Comment by pjsoftcoUser** [comment]
It should if nothing is blocking it but you can also find the driver installer in the installation folder in program files x86 and manually run it.

**Comment by pjsoftcoUser** [comment]
I’m closing this due to no response from the reporter!
