### ISSUE TITLE
[Feature Request] Add support for gyroscope

### ISSUE THREAD

**Issue by balbusm** [PJSoftCo/VGamepad#13]
Could you add support for gyroscope,
as some PS4 games require gyroscope movements.

**Comment by pjsoftcoUser** [comment]
Hi, thanks for reaching! Gyroscope is added to VGamepad but some phones do not have this sensor on them, you will get a notification saying ‘No Gyroscope detected on your phone’ in this case! All iPhones are equipped with this sensor but lots of Android phones are not!

**Comment by balbusm** [comment]
I'm using iPhone, but I can't pass below sequence.
No matter how I rotate the phone nothing happens. 
![image](https://user-images.githubusercontent.com/6872448/152239172-ae7c4885-88cf-486a-b6b2-c3762b16c48c.png)

**Comment by pjsoftcoUser** [comment]
Have you checked with PadTest.exe? You can also increase & decrease sensitivity in VGamepad! What type of iPhone do you have?

**Comment by balbusm** [comment]
I'm on iPhone 8 - iOS 15.3
Gyro works only if JoyCon is enabled.
Depicted pad rotates like crazy when iPhone is laying on the table
Gyro seems to be correctly calibrated as when Joy1+Motion is enabled, left joy behaves as you would expect 
![gyro](https://user-images.githubusercontent.com/6872448/152430362-391bd597-b4c3-4d56-8cd1-b7fb81a4746f.gif)

**Comment by pjsoftcoUser** [comment]
I just checked and also recorded a video for you, please take a look at it here: https://drive.google.com/file/d/1vrjrspt41Lqh1KH1TJN_KnJ1xaBHahm4/view?usp=drivesdk

**Comment by balbusm** [comment]
I did exactly how you said and I'm getting gyro readings with PadTest rotating all the time.

**Comment by pjsoftcoUser** [comment]
Then it's probably the type of phone! I will have to find an iPhone 8 and test through that to find the issue! Will let you know!

**Comment by damir2002-ms** [comment]
Hello! I can't connect my iphone to pc. The usb game is not showing up in windows settings. help me please

**Comment by pjsoftcoUser** [comment]
Please contact us on our Discord channel for help. this is not a bug to be here. thank you and sorry for the late response.

**Comment by pjsoftcoUser** [comment]
I also tested this feature using iPhone 8 and all looked good, not sure what your problem is if it still persists even.
