### ISSUE TITLE
Invalid Culture Name

### ISSUE THREAD

**Issue by JamieThul** [PJSoftCo/VGamepad#2]
Hey, looking to try this cool looking app out. However, on launching the program on my PC, I get an error, followed by a blank window. There error is:

The NeutralResourcesLanguageAttribute on the assembly "PcGameConsole, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" specifies an invalid culture name: "en-CK".

**Comment by pjsoftcoUser** [comment]
I will send you a custom build package and let me know if your issue gets resolved. just shoot an email to me at pjsoftco@outlook.com

**Comment by pjsoftcoUser** [comment]
The fix is in V5.2, thanks for bringing it up.
