### ISSUE TITLE
I finally got it to work using the vGamepad zip but...

### ISSUE THREAD

**Issue by GuessYouSuck** [PJSoftCo/VGamepad#20]
After it worked I wanted to test it out in Yuzu (nintendo switch emulator) but it seems that both of the joystick are drifting all the way toward the top left. If someone knows a fix please notify me. Thank you

**Comment by pjsoftcoUser** [comment]
Are you using the latest version of the app and server software?

**Comment by ProgramadorPocho** [comment]
I am having the same problem on IOS. Just downloaded a few hours ago and try it with steam. There is drift with the joysticks. I have the last version on IOS and V5.6 of the server.

**Comment by pjsoftcoUser** [comment]
Could you please provide a video and send it to our Discord channel? 
https://discord.gg/ZcAuAJp8py

**Comment by pjsoftcoUser** [comment]
Is this issue resolved? Can you provide a video?

**Comment by pjsoftcoUser** [comment]
Should be fixed now.
