### ISSUE TITLE
no Ip

### ISSUE THREAD

**Issue by JackyCox** [PJSoftCo/VGamepad#21]
No Ip address in the App after launch and before App starts there is a message
---------------------------
"Object reference not set to an instance of an object."
---------------------------

Faulting application name: VGamepadManager.exe, version: 1.0.0.0, time stamp: 0x646fc1a2
Faulting module name: clr.dll, version: 4.8.4645.0, time stamp: 0x648f6f63
Exception code: 0xc00000fd
Fault offset: 0x000000000003cd16
Faulting process id: 0x590

**Comment by pjsoftcoUser** [comment]
Hi, what windows do you use and do you have VPN setup on your machine?

**Comment by JackyCox** [comment]
Windows 10
Yes, i do have a few VPN apps

**Comment by JackyCox** [comment]
I fixed issue with Faulting module name: clr.dll by updating NetFramework
Message still popping up though and still no IP address

**Comment by pjsoftcoUser** [comment]
Probably those VPN apps has disrupted the settings on your machine, i would say resetting the network settings on your windows should fix the issue or removing the VPN, sometimes these VPNs are not standard and messes with the settings!

**Comment by pjsoftcoUser** [comment]
An update will be out soon for a more accurate way of reading internal IP.
