### ISSUE TITLE
Mac support please

### ISSUE THREAD

**Issue by gwthm-in** [PJSoftCo/VGamepad#23]

**Comment by Devil00303** [comment]
Hi, I found your application but the server app only exist for Windows OS but not for Mac OS.
Please can you create the macOS Server app ?

**Comment by pjsoftcoUser** [comment]
Mac gamer users are not that many and that is the reason we keep it to windows! You can always install windows on your mac and enjoy all of this, let us know if this is not a good solution.

**Comment by pjsoftcoUser** [comment]
Mac support has been added, here is the video of it:
https://youtu.be/TY_F3tA-5tI?si=Nh7jmmHhE8TwDJlo
