### ISSUE TITLE
can't use on win10 and iphone11

### ISSUE THREAD

**Issue by caoyaxing221** [PJSoftCo/VGamepad#24]
use ios 17.3，i got the green lcd but nothing prompt to install

**Comment by pjsoftcoUser** [comment]
Please install the driver by going to the application installation folder and run the exe file if you missed that step, windows firewall also prompts you to allow the connection, you have to allow it, otherwise it wont work!

**Comment by caoyaxing221** [comment]
> Please install the driver by going to the application installation folder and run the exe file if you missed that step, windows firewall also prompts you to allow the connection, you have to allow it, otherwise it wont work!

thanks,it worked,i forgot insatall the vigembussetup. But i can't use a and b buttton in the same time,can i use two buttons by push them together?

**Comment by pjsoftcoUser** [comment]
You should be able to! You can also turn off the continuous touch feature from settings if you are not getting the desired result.

**Comment by caoyaxing221** [comment]
thanks,it works.
