### ISSUE TITLE
no ip on Mac (vgamepad server)

### ISSUE THREAD

**Issue by nkteezzz** [PJSoftCo/VGamepad#26]
When starting vgamepad server an error appears (Value cannot be null.
Parameter name: value) and my ip is not displayed
![IMAGE 2024-03-06 17:11:23](https://github.com/PJSoftCo/VGamepad/assets/125863313/85876bf3-fb51-4ccb-80a0-67e223282e3b)
![IMAGE 2024-03-06 17:11:51](https://github.com/PJSoftCo/VGamepad/assets/125863313/4b333eb7-c06c-48bc-bd24-baa75d883c36)

**Comment by pjsoftcoUser** [comment]
Do you have VPN installed on your Mac? Are you connected through Wifi or LAN?

**Comment by nkteezzz** [comment]
У меня есть VPN TunnelBear, но я почти никогда не включаю его, я пытался запустить сервер с ним и без него, я еще не пытался его удалить. Я пользуюсь Интернетом через Wi-Fi, используя режим модема на своем iPhone. 

> У вас установлен VPN на вашем Mac? Вы подключены через Wi-Fi или локальную сеть?

**Comment by nkteezzz** [comment]
I have VPN TunnelBear, but I almost never turn it on, I tried running the server with and without it, I haven’t tried deleting it yet. I use the Internet via Wi-Fi using the modem mode in my iPhone.


> Do you have VPN installed on your Mac? Are you connected through Wifi or LAN?

**Comment by pjsoftcoUser** [comment]
I don't think you would be able to use VGamepad on your phone while your phone is also a hotspot for the wifi you use. You need to have a wifi router to connect to, then the server app should show the IP.

**Comment by edwinallan** [comment]
i have the same issue, a shame as i do not have a wifi router and the apple hotspot creates an ip so no reason for this (for instance i use touchosc in hotspot mode and it works great).

**Comment by pjsoftcoUser** [comment]
Closing since it is working as expected.
