### ISSUE TITLE
When i move the joystick my mouse moves

### ISSUE THREAD

**Issue by iWillPunchAMuffin** [PJSoftCo/VGamepad#4]
When i move my joystick the mouse moves which gets in the way for some games

**Comment by pjsoftcoUser** [comment]
That’s the feature that PCGameConsole gives you to control your desktop with the controller but it gets locked when you execute the game. Could you please collaborate more so i can understand what your problem is with this feature?

**Comment by pjsoftcoUser** [comment]
Closing on no response.
