### ISSUE TITLE
even with green light - still doesn't work

### ISSUE THREAD

**Issue by amirgelman** [PJSoftCo/VGamepad#5]
hey guys,
the app won't work.
i did everything including establishing the server (with server software)
plus I made sure the wifi is the same for all devcies and the app actually shows green light (meaning it's paired).

but the pad won't control anything on my dispay.
plus now the "xbox 360" joystick doesn't appear in my windows settings.

any idea what to do??

thank you!

**Comment by pjsoftcoUser** [comment]
Glad the solution mentioned on the youtube resolved the issue, hence i close this one.

Youtube response:
Do you see a new device under USB game controllers in windows? if not, you missed the bus driver installation step or denied it. PCGameConsole asks you to install the driver right after a successful connection to your phone. Now you can go to the software installation folder (Program files x86) and run the bus driver exe file to manually install the driver, let me know if this didn't work.

**Comment by evecimar** [comment]
thank you
