### ISSUE TITLE
https://github.com/PJSoftCo/VGamepad/blob/master/PCGameConsole_V6.7.zip

### ISSUE THREAD

**Issue by alannzi** [PJSoftCo/VGamepad#6]
https://github.com/PJSoftCo/VGamepad/blob/master/PCGameConsole_V6.7.zip

**Comment by pjsoftcoUser** [comment]
Could you please tell us what is the issue?

**Comment by pjsoftcoUser** [comment]
I’m going to close this since you did not provide any explanation.
