### ISSUE TITLE
d pad registration issue

### ISSUE THREAD

**Issue by alexguan8** [PJSoftCo/VGamepad#8]
Great app! Everything seems to work great except for the d pad (directional arrow buttons). It seems to register single taps as multiple most of the time, and in games that have you select between menu options it essentially makes the game unplayable, as a single tap will cause the highlighted item move by an arbitrary amount each time, no matter how short I try to make my tap on the screen.

**Comment by pjsoftcoUser** [comment]
Hi, thanks! Can you provide a video? I'm not sure what exactly happens? The shortest possible tap is 20ms which i think should not cause what you are saying but send me a video and i will investigate it!

**Comment by alexguan8** [comment]
Here's a video I took of the issue -- I tried recreating the issue on the iPad app but it seemed to be working fine. Could it be related to the smaller dimensions of the iPhone?
https://drive.google.com/file/d/1T1ngEAkQHBrOvDLy1UgDHOnXtnSlQkvU/view?usp=sharing

**Comment by alexguan8** [comment]
nevermind it seems to happen on the ipad app as well, just not as frequently

**Comment by alexguan8** [comment]
i think it has something to do with detecting movement during the singletap, as in it detects a slight change in the coordinate of the tap and registers another tap. It could probably be fixed pretty easily with an offset on registration of input if that's the case

**Comment by alexguan8** [comment]
It would make sense for it to be worse on smaller dimension screens because a slight change in coordinates would be registered as a larger number of taps, so perhaps the offset could be scaled by the dimension of the screen or something.

**Comment by pjsoftcoUser** [comment]
I can decrease the min tap duration to 0 for D-pad and see if it resolves your issue. I will issue an update shortly, let me know if it is resolved by then.

**Comment by pjsoftcoUser** [comment]
Sent the dl link to your school email.

**Comment by alexguan8** [comment]
I didn't get any emails on my school account

**Comment by alexguan8** [comment]
everything seems to be working fine now though after the latest update. thanks for the quick responses!

**Comment by pjsoftcoUser** [comment]
Did you install the one i sent you? You can also join our Discord community: https://discord.gg/ZcAuAJp8py

**Comment by alexguan8** [comment]
I never received an email on my school account from you, I just downloaded the update on the app store. It seems like when the issue happens I just restart the app and it starts working okay again. Not sure what the reason was

**Comment by pjsoftcoUser** [comment]
Okay, I updated the server-side software to include the fix, that should take care of the problem you have, install the lastest (not the app) and let me know if it is resolved. The app fix is related to faster connection establishment with server and also not going to sleep.

Thanks
